<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFM7bM66\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFM7bM66/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFM7bM66.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFM7bM66\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFM7bM66\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FM7bM66',
    'container.build_id' => '093d1653',
    'container.build_time' => 1533030299,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFM7bM66');
